### ISSUE TITLE
Phase 3

### ISSUE THREAD

**Issue by misoxxx** [misoxxx/sparse#2]
## Goals
- [x] __Finalize implementation__
    - [x]  Parsing of Revisions #12
    - [x] Parsing of TOC #11
    - [x] Program interface (program arguments, multiple files at once) #18 
- [x] __Prepare presentation for seminar__
    - Structure of the project
    - Design decisions
    - How is the tool run (To help other groups with phase 4)
